// This file is auto-generated by scripts/emit-version.js
export const sha = 'f5703ff';
export const buildTime = '2026-06-25T11:50:44.812Z';
export const version = 'dev';

export default { sha, buildTime, version };
