// This file is auto-generated by scripts/emit-version.js
export const sha = 'd3f9b38';
export const buildTime = '2026-07-28T11:14:52.042Z';
export const version = 'dev';

export default { sha, buildTime, version };
