// This file is auto-generated by scripts/emit-version.js
export const sha = '2d0157e';
export const buildTime = '2026-06-25T15:03:13.178Z';
export const version = 'dev';

export default { sha, buildTime, version };
