#![no_std]

//! Thin Soroban read client for the Stellar Intel reputation oracle.
//!
//! This crate is the on-chain-native consumer SDK: unlike the TypeScript and
//! Python SDKs, which wrap the `/api/reputation/*` REST surface, this crate
//! calls the deployed [`contracts/reputation`](https://github.com/ezedike-evan/stellar-intel/tree/main/contracts/reputation)
//! contract directly from within another Soroban contract's execution
//! context — there is no HTTP round trip. See `docs/ORACLE_SPEC.md` in the
//! main repository for the authoritative contract interface and the
//! deployed testnet contract id.
//!
//! It stays intentionally thin: a typed contract client for the oracle
//! (`ReputationClient`, generated by `#[contractclient]`) plus small typed
//! wrappers (`ReputationReader`) so consumer contracts don't have to
//! remember tuple field order for every read entrypoint.
//!
//! # Example
//!
//! ```ignore
//! use soroban_sdk::{Address, Env, String};
//! use stellar_intel_reputation::ReputationReader;
//!
//! fn read_score(env: Env, oracle: Address, anchor_id: String, corridor: String) {
//!     let reader = ReputationReader::new(&env, oracle);
//!     let score = reader.corridor_score(anchor_id, corridor);
//!     // score.composite_bps, score.fill_rate_bps, ...
//! }
//! ```

use soroban_sdk::{contractclient, contracttype, Address, Env, String, Vec};

/// Read entrypoints on the deployed reputation oracle contract, as declared
/// in `contracts/reputation/src/lib.rs`. `#[contractclient]` generates
/// [`ReputationClient`], a typed cross-contract client that dispatches each
/// method to the corresponding contract function by name.
#[contractclient(name = "ReputationClient")]
pub trait ReputationOracle {
    /// Every anchor id the oracle has an aggregate for.
    fn list_anchors(env: Env) -> Vec<String>;

    /// The last `n` outcome rows for an anchor, most recent first. Capped at
    /// 100 by the contract to bound gas consumption.
    fn recent_outcomes(env: Env, anchor_id: String, n: u32) -> Vec<(String, u64, bool)>;

    /// Rolling settlement totals for an (anchor, corridor) pair:
    /// `(total, successes, settle_seconds_sum)`. `(0, 0, 0)` when no
    /// outcomes have been recorded for that pair.
    fn get_corridor_aggregate(env: Env, anchor_id: String, corridor: String) -> (u32, u32, u64);

    /// Composite reputation score for an (anchor, corridor) pair:
    /// `(composite_bps, fill_rate_bps, settle_seconds_p50, n)`. `n` is the
    /// sample size the metrics were computed from; a score with `n == 0`
    /// has never had metrics published for that pair.
    fn get_score_for_corridor(
        env: Env,
        anchor_id: String,
        corridor: String,
    ) -> (i128, i128, u64, u32);

    /// The latest published block-level rate for a corridor, or `None` when
    /// none has been published. `rate` is scaled by 10^`decimals` fiat units
    /// per 1 USDC.
    fn get_corridor_rate(env: Env, corridor: String) -> Option<CorridorRate>;

    /// Cumulative volume and estimated savings for a corridor, or `None` when
    /// nothing has been recorded. Both figures are in microUSDC.
    fn get_volume_savings(env: Env, corridor: String) -> Option<VolumeSavings>;
}

/// A published corridor rate, mirroring `contracts/reputation/src/corridor_rate.rs`.
///
/// Declared here rather than imported: the contract crate is a `cdylib` and is
/// not a dependency of this one — that separation is the point of a thin read
/// SDK. The `#[contracttype]` layout must match the contract's, and the
/// integration tests deploy the real contract to check that it does.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CorridorRate {
    /// Scaled by 10^`decimals`, fiat units per 1 USDC.
    pub rate: i128,
    pub decimals: u32,
    /// Ledger timestamp of the publish.
    pub updated_at: u64,
    pub publisher: Address,
}

/// Cumulative volume and savings for a corridor, mirroring
/// `contracts/reputation/src/volume_savings.rs`.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VolumeSavings {
    /// Cumulative USDC volume settled, in microUSDC (1 USDC = 1_000_000).
    pub volume_usdc: i128,
    /// Cumulative estimated savings vs baseline, in microUSDC.
    pub savings_usdc: i128,
    pub settlement_count: u32,
    pub updated_at: u64,
    pub publisher: Address,
}

/// Summary of a reputation slice derived client-side from `recent_outcomes`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReputationAggregate {
    pub sample_size: u32,
    pub successful: u32,
    pub failed: u32,
    pub score_bps: u32,
}

impl ReputationAggregate {
    /// Returns the score as basis points for easy rendering and comparison.
    pub fn score(&self) -> u32 {
        self.score_bps
    }
}

/// Rolling settlement aggregate for a single (anchor, corridor) pair, as
/// maintained on-chain by `submit_outcome` and read via
/// `get_corridor_aggregate`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CorridorAggregate {
    pub total: u32,
    pub successes: u32,
    pub settle_seconds_sum: u64,
}

impl CorridorAggregate {
    /// Success rate in basis points. `0` when `total` is `0`.
    pub fn success_rate_bps(&self) -> u32 {
        if self.total == 0 {
            return 0;
        }
        self.successes.saturating_mul(10_000) / self.total
    }
}

/// Composite reputation score for a single (anchor, corridor) pair, as
/// computed on-chain by `get_score_for_corridor` from the metrics an admin
/// publishes via `set_corridor_metrics`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CorridorScore {
    /// Blended score in basis points, combining fill rate, slippage and
    /// settlement latency. `0` when no metrics have been published.
    pub composite_bps: i128,
    pub fill_rate_bps: i128,
    pub settle_seconds_p50: u64,
    /// Sample size the published metrics were computed from.
    pub sample_size: u32,
}

/// Typed wrapper around an oracle contract address.
pub struct ReputationReader<'a> {
    client: ReputationClient<'a>,
}

impl<'a> ReputationReader<'a> {
    /// Build a reader bound to a specific oracle contract address.
    pub fn new(env: &'a Env, contract_id: Address) -> Self {
        Self {
            client: ReputationClient::new(env, &contract_id),
        }
    }

    /// Every anchor id the oracle currently has an aggregate for.
    pub fn list_anchors(&self) -> Vec<String> {
        self.client.list_anchors()
    }

    /// Read the last `n` outcome rows for an anchor.
    pub fn recent_outcomes(&self, anchor_id: String, n: u32) -> Vec<(String, u64, bool)> {
        self.client.recent_outcomes(&anchor_id, &n)
    }

    /// Read the on-chain settlement aggregate for an (anchor, corridor)
    /// pair, exactly as stored by `submit_outcome`.
    pub fn corridor_aggregate(&self, anchor_id: String, corridor: String) -> CorridorAggregate {
        let (total, successes, settle_seconds_sum) =
            self.client.get_corridor_aggregate(&anchor_id, &corridor);
        CorridorAggregate {
            total,
            successes,
            settle_seconds_sum,
        }
    }

    /// Read the on-chain composite reputation score for an (anchor,
    /// corridor) pair, exactly as computed by `get_score_for_corridor`.
    pub fn corridor_score(&self, anchor_id: String, corridor: String) -> CorridorScore {
        let (composite_bps, fill_rate_bps, settle_seconds_p50, sample_size) =
            self.client.get_score_for_corridor(&anchor_id, &corridor);
        CorridorScore {
            composite_bps,
            fill_rate_bps,
            settle_seconds_p50,
            sample_size,
        }
    }

    /// Read the latest published rate for a corridor.
    ///
    /// `None` means no rate has ever been published for it — distinct from a
    /// rate of zero, which would be a real (and alarming) published value.
    pub fn corridor_rate(&self, corridor: String) -> Option<CorridorRate> {
        self.client.get_corridor_rate(&corridor)
    }

    /// Read cumulative volume and estimated savings for a corridor.
    ///
    /// `None` means nothing has been recorded yet. Both figures are in
    /// microUSDC: divide by 1_000_000 for USDC.
    pub fn volume_savings(&self, corridor: String) -> Option<VolumeSavings> {
        self.client.get_volume_savings(&corridor)
    }

    /// Read a compact aggregate over the last `window` outcomes.
    ///
    /// The aggregate is intentionally conservative and dependency-free:
    /// it derives a score from the observed success rate so consumer contracts
    /// can make deterministic read-only decisions.
    pub fn read_aggregate(&self, anchor_id: String, window: u32) -> ReputationAggregate {
        let outcomes = self.recent_outcomes(anchor_id, window);
        let sample_size = outcomes.len();
        if sample_size == 0 {
            return ReputationAggregate {
                sample_size: 0,
                successful: 0,
                failed: 0,
                score_bps: 0,
            };
        }

        let mut successful = 0u32;
        for (_, _, success) in outcomes.iter() {
            if success {
                successful += 1;
            }
        }

        let failed = sample_size - successful;
        let score_bps = successful.saturating_mul(10_000) / sample_size;

        ReputationAggregate {
            sample_size,
            successful,
            failed,
            score_bps,
        }
    }

    /// Convenience helper for consumer contracts that only need a score.
    pub fn score_bps(&self, anchor_id: String, window: u32) -> u32 {
        self.read_aggregate(anchor_id, window).score()
    }
}
