#!/usr/bin/env node
// Anchor fleet survey — reproducible classification of Stellar anchors by SEP support.
//
// Pulls every account tagged `anchor` from the stellar.expert public directory,
// fetches each domain's `stellar.toml`, and classifies it by the same keys the
// runtime uses in lib/stellar/server-rates.ts:
//
//   TRANSFER_SERVER          -> SEP-6  (programmatic deposit/withdraw)
//   TRANSFER_SERVER_SEP0024  -> SEP-24 (interactive hosted deposit/withdraw)
//   ANCHOR_QUOTE_SERVER      -> SEP-38 (firm-quote RFQ)
//   DIRECT_PAYMENT_SERVER    -> SEP-31 (cross-border payments)
//
// This is the script behind the "Anchor Fleet Status" section of maintainer.md.
// Re-run it to refresh the 41/11/30/51 snapshot and surface anchors that have
// since come online.
//
// Usage:
//   node scripts/anchor-survey.mjs            # human summary
//   node scripts/anchor-survey.mjs --json     # machine-readable JSON
//   node scripts/anchor-survey.mjs --json > anchors.json
//   node scripts/anchor-survey.mjs --recheck  # Markdown tables for docs/ANCHOR_FLEET_RECHECK.md
//
// Notes / caveats (see also docs + maintainer.md):
//   - The directory is NOT comprehensive (Stellar is permissionless). It also
//     lists anchors by their issuer/home domain, which is often distinct from the
//     service subdomain that actually hosts SEP endpoints (e.g. MoneyGram is listed
//     as `mgusd.moneygram.com` — issuer-only — while the live SEP-24 service runs
//     at `stellar.moneygram.com`). Treat the transfer-capable count as a FLOOR.
//   - "Transfer-capable" != "fiat off-ramp we care about": some hits are crypto
//     anchors or DEX gateways with no fiat corridor.

import { pathToFileURL } from 'node:url';

import { fetchDirectoryCandidates } from './lib/directory.mjs';
import { parseCurrencies } from './validate-anchors.mjs';

const DIRECTORY_URL = 'https://api.stellar.expert/explorer/public/directory?tag[]=anchor&limit=200';
const PER_ANCHOR_TIMEOUT_MS = 12_000;
const CONCURRENCY = 24;

const asJson = process.argv.includes('--json');
const asRecheck = process.argv.includes('--recheck');

// Notes carried into the recheck ledger for domains that map to a known anchor
// or are otherwise worth a second look. Keyed by directory domain.
const RECHECK_NOTES = {
  'cowrie.exchange': 'Listed anchor — home-domain probe only; SEP-24 service confirmed separately',
  'mgusd.moneygram.com': 'MoneyGram issuer domain; live service runs at stellar.moneygram.com',
  'mykobo.co': 'EUR off-ramp candidate (see #482)',
  'merge.lobstr.co': 'LOBSTR aggregator subdomain',
  'dead.apay.io': 'Legacy/retired subdomain',
  'old.repocoin.io': 'Legacy/retired subdomain',
  'old.sureremit.co': 'Legacy/retired subdomain',
};

// Human-readable symptom for an "unconfirmed" domain's failure reason.
function symptom(reason) {
  return (
    {
      'HTTP 400': 'HTTP 400 (bad request)',
      'HTTP 403': 'HTTP 403 (forbidden)',
      'HTTP 404': 'HTTP 404 (no toml)',
      'HTTP 521': 'HTTP 521 (origin down)',
      'TypeError:ENOTFOUND': 'DNS does not resolve',
      'TypeError:ECONNREFUSED': 'connection refused',
      'TypeError:ERR_TLS_CERT_ALTNAME_INVALID': 'TLS cert name mismatch',
      'TypeError:UNABLE_TO_GET_ISSUER_CERT_LOCALLY': 'TLS chain incomplete',
      AbortError: 'timed out mid-response',
    }[reason] ?? reason
  );
}

/**
 * Render the unreachable/unconfirmed Markdown tables for the fleet-recheck
 * ledger. "Unreachable" is the connection-timeout set (no TLS handshake);
 * everything else answered in some form but served no usable toml.
 */
function renderRecheck(dead, date) {
  const unreachable = dead
    .filter((d) => d.reason === 'TypeError:UND_ERR_CONNECT_TIMEOUT')
    .map((d) => d.domain)
    .sort();
  const unconfirmed = dead
    .filter((d) => d.reason !== 'TypeError:UND_ERR_CONNECT_TIMEOUT')
    .sort((a, b) => a.domain.localeCompare(b.domain));
  const note = (domain) => RECHECK_NOTES[domain] ?? '';

  const lines = [];
  lines.push(`<!-- generated by: node scripts/anchor-survey.mjs --recheck on ${date} -->`);
  lines.push(`## Unreachable (${unreachable.length})`, '');
  lines.push('| # | Domain | First seen | Last checked | Notes |');
  lines.push('|--:|---|---|---|---|');
  unreachable.forEach((domain, i) => {
    lines.push(`| ${i + 1} | \`${domain}\` | ${date} | ${date} | ${note(domain)} |`);
  });
  lines.push('', `## Unconfirmed (${unconfirmed.length})`, '');
  lines.push('| # | Domain | Symptom | Last checked | Notes |');
  lines.push('|--:|---|---|---|---|');
  unconfirmed.forEach((d, i) => {
    lines.push(
      `| ${i + 1} | \`${d.domain}\` | ${symptom(d.reason)} | ${date} | ${note(d.domain)} |`
    );
  });
  return lines.join('\n');
}

/** Pull the anchor-tagged directory and return the distinct domains. */
async function fetchAnchorDomains() {
  const candidates = await fetchDirectoryCandidates();
  const domains = new Set(candidates.map((candidate) => candidate.domain));
  return [...domains].sort();
}

/** Single fetch attempt; throws on network/TLS failure, returns null on non-200. */
async function attempt(url) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), PER_ANCHOR_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      redirect: 'follow',
      signal: ctrl.signal,
      headers: { 'User-Agent': 'stellar-intel-anchor-survey/1.0' },
    });
    if (!res.ok) return { status: res.status, toml: null };
    return { status: res.status, toml: await res.text() };
  } finally {
    clearTimeout(timer);
  }
}

/** Fetch a rail's `/info` JSON; same timeout/User-Agent as the TOML probe. */
async function fetchInfoJson(url) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), PER_ANCHOR_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      redirect: 'follow',
      signal: ctrl.signal,
      headers: { 'User-Agent': 'stellar-intel-anchor-survey/1.0' },
    });
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    try {
      return { ok: true, json: await res.json() };
    } catch {
      // Some anchors serve HTML or truncated bodies on /info; record it as a
      // failure rather than crashing the survey.
      const body = await res.text().catch(() => '');
      void body;
      return { ok: false, error: 'invalid JSON' };
    }
  } catch (err) {
    return {
      ok: false,
      error: `${err?.name ?? 'Error'}${err?.cause?.code ? `:${err.cause.code}` : ''}`,
    };
  } finally {
    clearTimeout(timer);
  }
}

const TOML_ENDPOINT_KEYS = {
  sep6: 'TRANSFER_SERVER',
  sep24: 'TRANSFER_SERVER_SEP0024',
  sep31: 'DIRECT_PAYMENT_SERVER',
  sep38: 'ANCHOR_QUOTE_SERVER',
  sep10: 'WEB_AUTH_ENDPOINT',
  sep12: 'KYC_SERVER',
};

/**
 * Pull SEP endpoint URLs out of a raw stellar.toml without a full TOML parse.
 * Line-anchored, quoted values only; only `https://` URLs are returned,
 * everything else is null (plain http, relative paths, missing keys).
 *
 * @param {string} toml
 * @returns {{ sep6: string | null, sep24: string | null, sep31: string | null,
 *   sep38: string | null, sep10: string | null, sep12: string | null }}
 */
export function parseTomlEndpoints(toml) {
  const out = { sep6: null, sep24: null, sep31: null, sep38: null, sep10: null, sep12: null };
  if (typeof toml !== 'string') return out;
  for (const [field, key] of Object.entries(TOML_ENDPOINT_KEYS)) {
    const match = new RegExp(`^\\s*${key}\\s*=\\s*["']([^"']+)["']`, 'im').exec(toml);
    const value = match?.[1]?.trim() ?? null;
    out[field] = value && value.startsWith('https://') ? value : null;
  }
  return out;
}

/** Codes whose entry has `enabled === true` (SEP-6/SEP-24 `/info` asset maps). */
function enabledCodes(node) {
  if (!node || typeof node !== 'object' || Array.isArray(node)) return [];
  return Object.entries(node)
    .filter(([, entry]) => entry?.enabled === true)
    .map(([code]) => code);
}

/**
 * Summarize a SEP-6/SEP-24 `GET /info` payload (port of the research probe):
 * enabled deposit/withdraw codes, enabled exchange codes, and per-code
 * withdraw `types` (e.g. `bank_account`) for withdraw entries that carry a
 * `types` object.
 *
 * @param {any} json
 * @returns {{ deposit: string[], withdraw: string[], depositExchange: string[],
 *   withdrawExchange: string[], withdrawTypes: Record<string, string[]> }}
 */
export function summarizeTransferInfo(json) {
  const src = json && typeof json === 'object' ? json : {};
  const withdrawNode = src.withdraw && typeof src.withdraw === 'object' ? src.withdraw : {};
  /** @type {Record<string, string[]>} */
  const withdrawTypes = {};
  for (const [code, entry] of Object.entries(withdrawNode)) {
    if (
      entry &&
      typeof entry === 'object' &&
      entry.types &&
      typeof entry.types === 'object' &&
      !Array.isArray(entry.types)
    ) {
      withdrawTypes[code] = Object.keys(entry.types).sort();
    }
  }
  return {
    deposit: enabledCodes(src.deposit),
    withdraw: enabledCodes(src.withdraw),
    depositExchange: enabledCodes(src['deposit-exchange']),
    withdrawExchange: enabledCodes(src['withdraw-exchange']),
    withdrawTypes,
  };
}

/**
 * Summarize a SEP-31 `GET /info` payload: receive codes whose entry is not
 * explicitly disabled (`enabled !== false`, so a missing flag still counts).
 *
 * @param {any} json
 * @returns {{ receive: string[] }}
 */
export function summarizeSep31Info(json) {
  const node = json?.receive && typeof json.receive === 'object' ? json.receive : {};
  const receive = Object.entries(node)
    .filter(([, entry]) => entry?.enabled !== false)
    .map(([code]) => code);
  return { receive };
}

/**
 * Summarize a SEP-38 `GET /info` payload: the advertised asset strings.
 *
 * @param {any} json
 * @returns {{ assets: string[] }}
 */
export function summarizeSep38Info(json) {
  const assets = Array.isArray(json?.assets)
    ? json.assets.map((entry) => entry?.asset).filter((asset) => typeof asset === 'string')
    : [];
  return { assets };
}

/**
 * Fetch + classify a single domain's stellar.toml. Retries once.
 *
 * On a reachable TOML the SEP endpoint URLs are parsed out and each present
 * rail's `/info` is fetched (same timeout/User-Agent): `rails.sep6`/`sep24`
 * carry the SEP-6/SEP-24 transfer summary, `sep31` the SEP-31 receive map,
 * `sep38` the SEP-38 asset list. Each rail is `{ url, ok: true, …summary }`
 * or `{ url, ok: false, error }`. `currencies` is the parsed [[CURRENCIES]].
 *
 * NOTE: Node's `fetch` (undici) verifies TLS and uses the runtime CA store, so a
 * domain with an expired/mismatched cert — or a runtime missing CA certs — fails
 * with TypeError ("fetch failed") even though `curl` (or a browser) might succeed.
 * `err.cause?.code` is captured so cross-environment drift is debuggable. The
 * authoritative reachable/transfer-capable split is the documented curl crawl; a
 * strict cert-verifying client legitimately sees fewer.
 */
export async function classify(domain) {
  const url = `https://${domain}/.well-known/stellar.toml`;
  let last;
  for (let i = 0; i < 2; i++) {
    try {
      const { status, toml } = await attempt(url);
      if (toml == null) return { domain, reachable: false, reason: `HTTP ${status}` };
      const has = (key) => new RegExp(`^\\s*${key}\\s*=`, 'im').test(toml);
      const endpoints = parseTomlEndpoints(toml);
      const result = {
        domain,
        reachable: true,
        sep6: has('TRANSFER_SERVER'),
        sep24: has('TRANSFER_SERVER_SEP0024'),
        sep38: has('ANCHOR_QUOTE_SERVER'),
        sep31: has('DIRECT_PAYMENT_SERVER'),
        currencies: parseCurrencies(toml),
        rails: {},
      };
      const railJobs = [];
      if (endpoints.sep6) {
        railJobs.push(
          fetchInfoJson(`${endpoints.sep6.replace(/\/$/, '')}/info`).then((info) => [
            'sep6',
            info.ok
              ? { url: endpoints.sep6, ok: true, ...summarizeTransferInfo(info.json) }
              : { url: endpoints.sep6, ok: false, error: info.error },
          ])
        );
      }
      if (endpoints.sep24) {
        railJobs.push(
          fetchInfoJson(`${endpoints.sep24.replace(/\/$/, '')}/info`).then((info) => [
            'sep24',
            info.ok
              ? { url: endpoints.sep24, ok: true, ...summarizeTransferInfo(info.json) }
              : { url: endpoints.sep24, ok: false, error: info.error },
          ])
        );
      }
      if (endpoints.sep31) {
        railJobs.push(
          fetchInfoJson(`${endpoints.sep31.replace(/\/$/, '')}/info`).then((info) => [
            'sep31',
            info.ok
              ? { url: endpoints.sep31, ok: true, ...summarizeSep31Info(info.json) }
              : { url: endpoints.sep31, ok: false, error: info.error },
          ])
        );
      }
      if (endpoints.sep38) {
        railJobs.push(
          fetchInfoJson(`${endpoints.sep38.replace(/\/$/, '')}/info`).then((info) => [
            'sep38',
            info.ok
              ? { url: endpoints.sep38, ok: true, ...summarizeSep38Info(info.json) }
              : { url: endpoints.sep38, ok: false, error: info.error },
          ])
        );
      }
      for (const [rail, summary] of await Promise.all(railJobs)) {
        result.rails[rail] = summary;
      }
      return result;
    } catch (err) {
      last = `${err?.name ?? 'Error'}${err?.cause?.code ? `:${err.cause.code}` : ''}`;
    }
  }
  return { domain, reachable: false, reason: last };
}

/** Map over items with a fixed concurrency limit. */
async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let i = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      out[idx] = await fn(items[idx]);
    }
  });
  await Promise.all(workers);
  return out;
}

async function main() {
  const domains = await fetchAnchorDomains();
  const results = await mapLimit(domains, CONCURRENCY, classify);

  const live = results.filter((r) => r.reachable);
  const dead = results.filter((r) => !r.reachable);
  const any6 = live.filter((r) => r.sep6);
  const any24 = live.filter((r) => r.sep24);
  const both = live.filter((r) => r.sep6 && r.sep24);
  const only6 = live.filter((r) => r.sep6 && !r.sep24);
  const only24 = live.filter((r) => r.sep24 && !r.sep6);
  const transferCapable = live.filter((r) => r.sep6 || r.sep24);
  const issuerOnly = live.filter((r) => !r.sep6 && !r.sep24);

  if (asRecheck) {
    console.log(renderRecheck(dead, new Date().toISOString().slice(0, 10)));
    return;
  }

  if (asJson) {
    console.log(
      JSON.stringify(
        {
          generatedAt: new Date().toISOString(),
          source: DIRECTORY_URL,
          totals: {
            tagged: domains.length,
            reachable: live.length,
            unreachable: dead.length,
            transferCapable: transferCapable.length,
            issuerOnly: issuerOnly.length,
            sep6: any6.length,
            sep24: any24.length,
            both: both.length,
            only6: only6.length,
            only24: only24.length,
            sep38: live.filter((r) => r.sep38).length,
            sep31: live.filter((r) => r.sep31).length,
          },
          transferCapableDomains: transferCapable.map((r) => r.domain),
          issuerOnlyDomains: issuerOnly.map((r) => r.domain),
          unreachableDomains: dead.map((r) => r.domain),
          results,
        },
        null,
        2
      )
    );
    return;
  }

  const line = (label, n) => console.log(`  ${label.padEnd(28)}${n}`);
  console.log(`Stellar anchor fleet survey — ${new Date().toISOString()}`);
  console.log(`Source: ${DIRECTORY_URL}\n`);
  line('directory-tagged domains:', domains.length);
  line('stellar.toml reachable:', live.length);
  line('unreachable / no toml:', dead.length);
  console.log(`\nOf the ${live.length} live tomls:`);
  line('transfer-capable:', transferCapable.length);
  line('issuer-only:', issuerOnly.length);
  line('SEP-6 (any):', any6.length);
  line('SEP-24 (any):', any24.length);
  line('SEP-6 only:', only6.length);
  line('SEP-24 only:', only24.length);
  line('both SEP-6 & SEP-24:', both.length);
  line('also SEP-38 quotes:', live.filter((r) => r.sep38).length);
  line('also SEP-31 payments:', live.filter((r) => r.sep31).length);
  console.log(`\nTransfer-capable: ${transferCapable.map((r) => r.domain).join(', ')}`);
}

// Guard the run so the module stays importable for tests (parseTomlEndpoints
// et al.) without kicking off a full survey crawl on import.
const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
