const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const { resolve } = require('path');

function gitShortSha() {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch (e) {
    // CI build hosts often check out without git metadata, so `git rev-parse`
    // throws and the footer renders "v unknown" — which it did in production.
    // Vercel exposes the commit directly; fall back to that before giving up.
    const ciSha =
      process.env.VERCEL_GIT_COMMIT_SHA ||
      process.env.GITHUB_SHA ||
      process.env.CF_PAGES_COMMIT_SHA;
    return ciSha ? ciSha.slice(0, 7) : 'unknown';
  }
}

function isoNow() {
  return new Date().toISOString();
}

const sha = gitShortSha();
const buildTime = isoNow();
const version = process.env.NEXT_PUBLIC_APP_VERSION || 'dev';

const out = `// This file is auto-generated by scripts/emit-version.js
export const sha = '${sha}';
export const buildTime = '${buildTime}';
export const version = '${version}';

export default { sha, buildTime, version };
`;

const target = resolve(process.cwd(), 'lib', 'version.ts');
writeFileSync(target, out, { encoding: 'utf8' });
console.log(`Wrote version to ${target}: ${sha} @ ${buildTime}`);
