import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

function gitShortSha() {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch (e) {
    return 'unknown';
  }
}

function isoNow() {
  return new Date().toISOString();
}

const sha = gitShortSha();
const buildTime = isoNow();

const out = `// This file is auto-generated by scripts/emit-version.ts
export const sha = '${sha}';
export const buildTime = '${buildTime}';
export const version = '${process.env.NEXT_PUBLIC_APP_VERSION ?? 'dev'}';

export default { sha, buildTime, version };
`;

const target = resolve(process.cwd(), 'lib', 'version.ts');
writeFileSync(target, out, { encoding: 'utf8' });
console.log(`Wrote version to ${target}: ${sha} @ ${buildTime}`);
