const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const { resolve } = require('path');

function gitShortSha() {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch (e) {
    return 'unknown';
  }
}

function isoNow() {
  return new Date().toISOString();
}

const sha = gitShortSha();
const buildTime = isoNow();
const version = process.env.NEXT_PUBLIC_APP_VERSION || 'dev';

const out = `// This file is auto-generated by scripts/emit-version.js
export const sha = '${sha}';
export const buildTime = '${buildTime}';
export const version = '${version}';

export default { sha, buildTime, version };
`;

const target = resolve(process.cwd(), 'lib', 'version.ts');
writeFileSync(target, out, { encoding: 'utf8' });
console.log(`Wrote version to ${target}: ${sha} @ ${buildTime}`);
